version: '3.6'
services:
  hasura:
    image: hasura/graphql-engine:v2.28.2
    restart: "always"
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://orbios:wf3354%25%23re@159.65.133.226:5432/orbios_hub
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: 6hw3$@1&xAsZpE!k@rj
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"7dc88f8d7d2668f01a805b462e9eb51c9d4fccee1a32d0df34758798084a3108"}'
